// <auto-generated />
using System;
using MenuApiV2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenuApiV2.Migrations
{
    [DbContext(typeof(FoodAppDbContext))]
    [Migration("20251002164217_Migration2")]
    partial class Migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MenuApiV2.Models.Cook", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("C_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Certificate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CId")
                        .HasName("PK__Cook__A9FDEC127251B792");

                    b.ToTable("Cook", (string)null);
                });

            modelBuilder.Entity("MenuApiV2.Models.Customer", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("C_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PaymentOpt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CId")
                        .HasName("PK__Customer__A9FDEC12938DD7D0");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("MenuApiV2.Models.DeliveryCyclist", b =>
                {
                    b.Property<int>("DcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DC_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DcId"));

                    b.Property<string>("BikeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("DcId")
                        .HasName("PK__Delivery__46564CF923AA2834");

                    b.ToTable("Delivery_Cyclist", (string)null);
                });

            modelBuilder.Entity("MenuApiV2.Models.Meal", b =>
                {
                    b.Property<int>("MId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("M_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MId"));

                    b.Property<int>("CookId")
                        .HasColumnType("int")
                        .HasColumnName("CookID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int")
                        .HasColumnName("QTY");

                    b.Property<TimeOnly>("TimeEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TimeStart")
                        .HasColumnType("time");

                    b.HasKey("MId")
                        .HasName("PK__Meal__18B1A3178C6A276D");

                    b.HasIndex("CookId");

                    b.ToTable("Meal", (string)null);
                });

            modelBuilder.Entity("MenuApiV2.Models.Order", b =>
                {
                    b.Property<int>("OId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("O_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OId"));

                    b.Property<int>("CId")
                        .HasColumnType("int")
                        .HasColumnName("C_ID");

                    b.Property<DateTime>("ODate")
                        .HasColumnType("datetime")
                        .HasColumnName("O_DATE");

                    b.HasKey("OId")
                        .HasName("PK__Order__5AAB0C183571FF88");

                    b.HasIndex("CId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("MenuApiV2.Models.OrderDetail", b =>
                {
                    b.Property<int>("OId")
                        .HasColumnType("int")
                        .HasColumnName("O_ID");

                    b.Property<int>("MId")
                        .HasColumnType("int")
                        .HasColumnName("M_ID");

                    b.Property<int>("Qty")
                        .HasColumnType("int")
                        .HasColumnName("QTY");

                    b.HasKey("OId", "MId")
                        .HasName("PK__Order_De__3B201629AE535250");

                    b.HasIndex("MId");

                    b.ToTable("Order_Details", (string)null);
                });

            modelBuilder.Entity("MenuApiV2.Models.Rating", b =>
                {
                    b.Property<int>("RId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("R_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RId"));

                    b.Property<int>("CId")
                        .HasColumnType("int")
                        .HasColumnName("C_ID");

                    b.Property<int?>("CStars")
                        .HasColumnType("int")
                        .HasColumnName("C_STARS");

                    b.Property<int?>("CookId")
                        .HasColumnType("int")
                        .HasColumnName("CookID");

                    b.Property<int?>("DcId")
                        .HasColumnType("int")
                        .HasColumnName("DC_ID");

                    b.Property<int?>("DcStars")
                        .HasColumnType("int")
                        .HasColumnName("DC_STARS");

                    b.Property<int>("OId")
                        .HasColumnType("int")
                        .HasColumnName("O_ID");

                    b.HasKey("RId")
                        .HasName("PK__Rating__DE152E8970A20A71");

                    b.HasIndex("CId");

                    b.HasIndex("CookId");

                    b.HasIndex("DcId");

                    b.HasIndex("OId");

                    b.ToTable("Rating", (string)null);
                });

            modelBuilder.Entity("MenuApiV2.Models.Trip", b =>
                {
                    b.Property<int>("TId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("T_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TId"));

                    b.Property<int>("DcId")
                        .HasColumnType("int")
                        .HasColumnName("DC_ID");

                    b.Property<int>("OId")
                        .HasColumnType("int")
                        .HasColumnName("O_ID");

                    b.Property<int>("TTime")
                        .HasColumnType("int")
                        .HasColumnName("T_Time");

                    b.Property<int>("TripPay")
                        .HasColumnType("int");

                    b.HasKey("TId")
                        .HasName("PK__Trip__83BB1FB2666AB6D8");

                    b.HasIndex("DcId");

                    b.HasIndex("OId");

                    b.ToTable("Trip", (string)null);
                });

            modelBuilder.Entity("MenuApiV2.Models.TripDetail", b =>
                {
                    b.Property<int>("TId")
                        .HasColumnType("int")
                        .HasColumnName("T_ID");

                    b.Property<TimeOnly>("TimeStamp")
                        .HasColumnType("time")
                        .HasColumnName("Time_Stamp");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TId", "TimeStamp")
                        .HasName("PK__Trip_Det__3881C38E1EBAD5DF");

                    b.ToTable("Trip_Details", (string)null);
                });

            modelBuilder.Entity("MenuApiV2.Models.Meal", b =>
                {
                    b.HasOne("MenuApiV2.Models.Cook", "Cook")
                        .WithMany("Meals")
                        .HasForeignKey("CookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Meal__CookID__753864A1");

                    b.Navigation("Cook");
                });

            modelBuilder.Entity("MenuApiV2.Models.Order", b =>
                {
                    b.HasOne("MenuApiV2.Models.Customer", "CIdNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("CId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Order__C_ID__7DCDAAA2");

                    b.Navigation("CIdNavigation");
                });

            modelBuilder.Entity("MenuApiV2.Models.OrderDetail", b =>
                {
                    b.HasOne("MenuApiV2.Models.Meal", "MIdNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("MId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Order_Deta__M_ID__019E3B86");

                    b.HasOne("MenuApiV2.Models.Order", "OIdNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Order_Deta__O_ID__00AA174D");

                    b.Navigation("MIdNavigation");

                    b.Navigation("OIdNavigation");
                });

            modelBuilder.Entity("MenuApiV2.Models.Rating", b =>
                {
                    b.HasOne("MenuApiV2.Models.Customer", "CIdNavigation")
                        .WithMany("Ratings")
                        .HasForeignKey("CId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Rating__C_ID__0EF836A4");

                    b.HasOne("MenuApiV2.Models.Cook", "Cook")
                        .WithMany("Ratings")
                        .HasForeignKey("CookId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Rating__CookID__0E04126B");

                    b.HasOne("MenuApiV2.Models.DeliveryCyclist", "Dc")
                        .WithMany("Ratings")
                        .HasForeignKey("DcId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Rating__DC_ID__0FEC5ADD");

                    b.HasOne("MenuApiV2.Models.Order", "OIdNavigation")
                        .WithMany("Ratings")
                        .HasForeignKey("OId")
                        .IsRequired()
                        .HasConstraintName("FK__Rating__O_ID__10E07F16");

                    b.Navigation("CIdNavigation");

                    b.Navigation("Cook");

                    b.Navigation("Dc");

                    b.Navigation("OIdNavigation");
                });

            modelBuilder.Entity("MenuApiV2.Models.Trip", b =>
                {
                    b.HasOne("MenuApiV2.Models.DeliveryCyclist", "Dc")
                        .WithMany("Trips")
                        .HasForeignKey("DcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Trip__DC_ID__056ECC6A");

                    b.HasOne("MenuApiV2.Models.Order", "OIdNavigation")
                        .WithMany("Trips")
                        .HasForeignKey("OId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Trip__O_ID__047AA831");

                    b.Navigation("Dc");

                    b.Navigation("OIdNavigation");
                });

            modelBuilder.Entity("MenuApiV2.Models.TripDetail", b =>
                {
                    b.HasOne("MenuApiV2.Models.Trip", "TIdNavigation")
                        .WithMany("TripDetails")
                        .HasForeignKey("TId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Trip_Detai__T_ID__084B3915");

                    b.Navigation("TIdNavigation");
                });

            modelBuilder.Entity("MenuApiV2.Models.Cook", b =>
                {
                    b.Navigation("Meals");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("MenuApiV2.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("MenuApiV2.Models.DeliveryCyclist", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("MenuApiV2.Models.Meal", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("MenuApiV2.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Ratings");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("MenuApiV2.Models.Trip", b =>
                {
                    b.Navigation("TripDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
